# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build with JDK${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # LTS and the latest one
        jdk: [ 8 ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
